apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-working-6
  labels:
    app: {{ .Chart.Name }}-working-6
    app.kubernetes.io/name: {{ .Chart.Name }}-working-6
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: nginx-fail-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-working-6
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-working-6
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          name: http
