apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-working-2
  labels:
    app: {{ .Chart.Name }}-working-2
    app.kubernetes.io/name: {{ .Chart.Name }}-working-2
    app.kubernetes.io/instance: {{ .Chart.Name }}-working-2
    app.kubernetes.io/part-of: nginx-fail-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-working-2
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
