apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-working
  labels:
    app: {{ .Chart.Name }}-working
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-working
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
